language: generic
os:
- linux
sudo: false
dist: trusty
env:
  global:
  - DEVKITARM=$HOME/devkitARM
addons:
  apt:
    packages:
    - gcc-multilib
    - linux-libc-dev
cache:
  apt: true
install:
- cd $HOME
- travis_retry wget http://download.sourceforge.net/devkitpro/devkitARM_r46-x86_64-linux.tar.bz2
- tar xf devkitARM*.tar.bz2
- travis_retry git clone https://github.com/YamaArashi/agbcc.git
- cd agbcc && ./build.sh && ./install.sh $TRAVIS_BUILD_DIR
script:
- cd $TRAVIS_BUILD_DIR
- travis_retry wget -q $BASEROM_URL -O baserom.gba
- ./build_tools.sh
- make tidy && make -j2 compare_ruby
- make tidy && make -j2 compare_ruby_rev1
- make tidy && make -j2 compare_ruby_rev2
- make tidy && make -j2 compare_sapphire
- make tidy && make -j2 compare_sapphire_rev1
- make tidy && make -j2 compare_sapphire_rev2
