language: generic
dist: trusty
sudo: false
env:
  global:
    - DEVKITARM=$HOME/devkitARM
addons:
  apt:
    packages:
      - gcc-multilib
      - linux-libc-dev
cache:
  apt: true
install:
  - pushd $HOME
  - travis_retry wget http://download.sourceforge.net/devkitpro/devkitARM_r46-x86_64-linux.tar.bz2
  - tar xf devkitARM*.tar.bz2
  - travis_retry git clone https://github.com/pret/agbcc.git
  - cd agbcc && ./build.sh && ./install.sh $TRAVIS_BUILD_DIR
  - popd

matrix:
  include:
    - os: linux
      env: _="Build"
      before_script:
        - touch baserom-debug.gba
      script:
        - ./build_tools.sh
        - make -j2 compare_ruby
        - make -j2 compare_ruby_rev1
        - make -j2 compare_ruby_rev2
        - make -j2 compare_sapphire
        - make -j2 compare_sapphire_rev1
        - make -j2 compare_sapphire_rev2
    - os: linux
      env: _="Formatting"
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty
          packages:
            - clang-format-5.0
            - colordiff
      install: [ ]
      before_script:
        - cp .travis/colordiffrc ~/.colordiffrc
      script:
        .travis/check-git-clang-format-output.sh
    - os: linux
      env: _="Build German"
      before_script:
        - touch baserom-debug.gba
        - cp override-de.mk override.mk
        - rsync -avhI asm-de/ asm/
        - rsync -avhI data-de/ data/
        - rsync -avhI graphics-de/ graphics/
      script:
        - ./build_tools.sh
        - make -j2 compare_ruby_de
    - os: linux
      env: _="Build German debug"
      before_script:
        - dd if=/dev/zero of=baserom-debug.gba bs=1048576 count=16 # 16 MiB
        - cp override-de.mk override.mk
        - rsync -avhI asm-de/ asm/
        - rsync -avhI data-de/ data/
        - rsync -avhI graphics-de/ graphics/
      script:
        - ./build_tools.sh
        - make -j2 ruby_de_debug
  allow_failures:
    - env: _="Formatting"
